GAMESTATE = {}

GAMESTATE.STATE = {}
GAMESTATE.STATE.START = "start"
GAMESTATE.STATE.NARRATIVE = "narrative"
GAMESTATE.STATE.MENU = "menu"
GAMESTATE.STATE.GAME = "game"
GAMESTATE.STATE.GAMEOVER = "gameOver"
GAMESTATE.STATE.WIN = "win"

GAMESTATE.currentState = "start"

return GAMESTATE
