WEAPONS = {}

WEAPONS.IMGPATH = "contents/images/weapons"

WEAPONS.TYPE = {}
WEAPONS.TYPE.HERO_MAGIC_STAFF = "hero_magic_staff"
WEAPONS.TYPE.MAGIC_STAFF = "magic_staff"
WEAPONS.TYPE.SWORD = "sword"
WEAPONS.TYPE.FLOWER = "flower"
WEAPONS.TYPE.AXE = "axe"
WEAPONS.TYPE.DOUBLE_AXE = "double_axe"

WEAPONS.STATE = {}
WEAPONS.STATE.IDLE = "idle"
WEAPONS.STATE.FIRE = "fire"

return WEAPONS
