-- FICHIER DE CONFIGURATION QUI CONTIENT LES ETATS ET TYPES DE PERSONNAGES POSSIBLES
CHARACTERS = {}

CHARACTERS.IMGPATH = "contents/images/characters"

CHARACTERS.CATEGORY = {}
CHARACTERS.CATEGORY.PLAYER = "player"
CHARACTERS.CATEGORY.ENNEMY = "ennemy"

CHARACTERS.TYPE = {}
CHARACTERS.TYPE.ORC = "orc"
CHARACTERS.TYPE.KNIGHT = "knight"
CHARACTERS.TYPE.MAGE = "mage"
CHARACTERS.TYPE.PRINCESS = "princess"
CHARACTERS.TYPE.DWARF = "dwarf"

CHARACTERS.MODE = {}
CHARACTERS.MODE.NORMAL = "normal"
CHARACTERS.MODE.BOOSTED = "boosted"

CHARACTERS.STATE = {}
CHARACTERS.STATE.IDLE = "IDLE"
CHARACTERS.STATE.ALERT = "ALERT"
CHARACTERS.STATE.WALKING = "WALKING"
CHARACTERS.STATE.FIRE = "FIRE"
CHARACTERS.STATE.DEAD = "DEAD"

return CHARACTERS
